# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('contect', models.CharField(max_length=300)),
                ('ptime', models.DateTimeField(auto_now=True)),
                ('pcontect', models.CharField(max_length=250)),
                ('pphoot', models.CharField(max_length=500)),
                ('htime', models.DateTimeField(auto_now=True)),
                ('hcontect', models.CharField(max_length=250)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.User', to_field='username')),
            ],
            options={
                'db_table': 'user_blog',
            },
        ),
        migrations.AlterField(
            model_name='user_villalist',
            name='bathroom_photo',
            field=models.CharField(default='/static/assets/img/icon/shawer.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='user_villalist',
            name='bedroom_photo',
            field=models.CharField(default='/static/assets/img/icon/bed.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='user_villalist',
            name='garage_photo',
            field=models.CharField(default='/static/assets/img/icon/cars.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='user_weivilla',
            name='weivilla_photo',
            field=models.CharField(default='/static/assets/img/demo/property-1.jpg', max_length=500),
        ),
    ]
