# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190706_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_tuijian',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tuijian_photo', models.CharField(default='/static/assets/img/demo/small-property-2.jpg', max_length=500)),
            ],
            options={
                'db_table': 'user_tuijian',
            },
        ),
    ]
