# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-07 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_user_tuijian_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_stylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50, unique=True)),
                ('stype', models.CharField(max_length=20)),
                ('semail', models.EmailField(max_length=30)),
                ('sphone', models.CharField(max_length=11)),
                ('saddress', models.CharField(max_length=200)),
                ('signature', models.CharField(max_length=200)),
                ('sphoto', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user_stylist',
            },
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='pphoot',
            new_name='pphoto',
        ),
    ]
