# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-07 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190707_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_weivilla',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
