# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20190707_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usertype',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '管理员')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_sex',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0),
        ),
    ]
