# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-08 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20190708_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_sex',
            new_name='sex',
        ),
    ]
