# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20190708_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Blog',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('ptime', models.DateTimeField(auto_now=True)),
                ('pcontect', models.CharField(max_length=250)),
                ('pphoto', models.CharField(default="{% static 'assets/img/client-face2.png'%}", max_length=500)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.User', to_field='username')),
            ],
            options={
                'db_table': 'user_Blog',
            },
        ),
    ]
