# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-11 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_user_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_xiangqing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('money', models.IntegerField(null=True)),
                ('miaoshu', models.CharField(max_length=500)),
                ('photo', models.CharField(default='/static/assets/img/property-1/property3.jpg"', max_length=500, null=True)),
            ],
            options={
                'db_table': 'user_xiangqing',
            },
        ),
    ]
