# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-11 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_user_xiangqing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_villalist',
            name='tid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
