# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-12 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20190712_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_weivilla',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
